services:
  database:
    build:
      dockerfile: /database/Dockerfile
      context: .
    restart: always
    ports:
      - 1433:1433
    volumes:
      - database:/var/opt/mssql
    env_file:
      - ./database/.env

  next:
    build:
      dockerfile: /frontend/Dockerfile
      context: .
    restart: always

  cache:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

volumes:
  database: null
