import { Listing } from './Listing'

export interface ExtendedListing extends Listing {
  listingUrl: string,
  summary: string,
  space: string,
  description: string,
  experiencesOffered: string,
  neighborhoodOverview: string,
  notes: string,
  transit: string,
  access: string,
  interaction: string,
  houseRules: string,
  thumbnailUrl: string,
  mediumUrl: string,
  pictureUrl: string,
  xlPictureUrl: string,
  hostId: number,
  hostUrl: string,
  hostName: string,
  hostSince: string,
  hostLocation: string,
  hostAbout: string,
  hostResponseTime: string,
  hostResponseRate: string,
  hostAcceptanceRate: string,
  hostIsSuperhost: string,
  hostThumbnailUrl: string,
  hostPictureUrl: string,
  hostNeighbourhood: string | null,
  hostListingsCount: number,
  hostTotalListingsCount: number,
  hostVerifications: string,
  hostHasProfilePic: string,
  hostIdentityVerified: string,
  street: string,
  neighbourhood: string | null,
  neighbourhoodCleansed: string,
  neighbourhoodGroupCleansed: string | null,
  city: string,
  state: string,
  zipcode: string,
  market: string,
  smartLocation: string,
  countryCode: string,
  country: string,
  isLocationExact: string,
  propertyType: string,
  roomType: string,
  accommodates: number,
  bathrooms: number,
  bedrooms: number,
  beds: number,
  bedType: string,
  amenities: string,
  squareFeet: number | null,
  weeklyPrice: string,
  monthlyPrice: string,
  securityDeposit: string,
  cleaningFee: string,
  guestsIncluded: number,
  extraPeople: string,
  minimumNights: number,
  maximumNights: number,
  calendarUpdated: string,
  hasAvailability: string,
  availability30: number,
  availability60: number,
  availability90: number,
  availability365: number,
  calendarLastScraped: string,
  numberOfReviews: number,
  firstReview: string,
  lastReview: string,
  reviewScoresRating: number,
  reviewScoresAccuracy: number,
  reviewScoresCleanliness: number,
  reviewScoresCheckin: number,
  reviewScoresCommunication: number,
  reviewScoresLocation: number,
  reviewScoresValue: number,
  requiresLicense: string,
  license: string | null,
  jurisdictionNames: string,
  instantBookable: string,
  isBusinessTravelReady: string,
  cancellationPolicy: string,
  requireGuestProfilePicture: string,
  requireGuestPhoneVerification: string,
  calculatedHostListingsCount: number,
  reviewsPerMonth: number,
}
